# Generated by Django 4.1 on 2024-02-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='excelnandhu@gmail.com', max_length=54),
        ),
    ]
